# KERNELIZE Services Module

# Core compression and query services
from .compression_engine import (
    compression_engine,
    compress_knowledge,
    KernelCompressionEngine,
    SemanticCompressor,
    EntityExtractor,
    RelationshipExtractor,
    CompressionResult,
    Entity,
    Relationship,
    CausalChain,
    CompressionLevel,
)
from .query_engine import (
    query_engine,
    semantic_search,
    hybrid_search,
    KernelQueryEngine,
    CacheManager,
    EmbeddingGenerator,
    ExactMatcher,
    HybridSearchEngine,
    QueryResult,
    QueryMetrics,
    QueryType,
)

# Priority 2: Query and Reasoning Capabilities
from .storage import (
    PostgreSQLStorageBackend,
    KernelStorageSchema,
    KernelMetadata,
    KernelVersion,
    DocumentRecord,
    ChunkRecord,
    RelationshipRecord,
    EntityType,
    RelationshipType,
    KernelExporter,
    KernelImporter,
    KernelDiff,
    ExportFormat,
    EncryptionMode,
    ExportOptions,
    ImportOptions,
    ImportResult,
)

from .query import (
    QueryIntent,
    QueryOperator,
    QueryUnderstandingPipeline,
    QueryCache,
    understand_query,
    QueryRewrite,
    QueryComponent,
    ExtractedEntity,
    TemporalConstraint,
)

from .reasoning import (
    ReasoningType,
    EvidenceSource,
    MultiHopReasoningEngine,
    QuestionDecomposer,
    EvidenceCollector,
    ReasoningChainExecutor,
    ConfidenceAggregator,
    ExplanationGenerator,
    ReasoningTrace,
    ReasoningStep,
    Evidence,
    SubQuestion,
    MultiHopResult,
    CausalRelationType,
    CausalQueryType,
    CausalReasoningEngine,
    CausalGraphBuilder,
    CausalPatternExtractor,
    CounterfactualEngine,
    CausalExplanation,
    CausalNode,
    CausalEdge,
    CausalPath,
    CounterfactualScenario,
)

__all__ = [
    # Compression
    "compression_engine",
    "compress_knowledge",
    "KernelCompressionEngine",
    "SemanticCompressor",
    "EntityExtractor",
    "RelationshipExtractor",
    "CompressionResult",
    "Entity",
    "Relationship",
    "CausalChain",
    "CompressionLevel",
    # Query
    "query_engine",
    "semantic_search",
    "hybrid_search",
    "KernelQueryEngine",
    "CacheManager",
    "EmbeddingGenerator",
    "ExactMatcher",
    "HybridSearchEngine",
    "QueryResult",
    "QueryMetrics",
    "QueryType",
    # Storage
    "PostgreSQLStorageBackend",
    "KernelStorageSchema",
    "KernelMetadata",
    "KernelVersion",
    "DocumentRecord",
    "ChunkRecord",
    "RelationshipRecord",
    "EntityType",
    "RelationshipType",
    "KernelExporter",
    "KernelImporter",
    "KernelDiff",
    "ExportFormat",
    "EncryptionMode",
    "ExportOptions",
    "ImportOptions",
    "ImportResult",
    # Query Understanding
    "QueryIntent",
    "QueryOperator",
    "QueryUnderstandingPipeline",
    "QueryCache",
    "understand_query",
    "QueryRewrite",
    "QueryComponent",
    "ExtractedEntity",
    "TemporalConstraint",
    # Reasoning
    "ReasoningType",
    "EvidenceSource",
    "MultiHopReasoningEngine",
    "QuestionDecomposer",
    "EvidenceCollector",
    "ReasoningChainExecutor",
    "ConfidenceAggregator",
    "ExplanationGenerator",
    "ReasoningTrace",
    "ReasoningStep",
    "Evidence",
    "SubQuestion",
    "MultiHopResult",
    # Causal Reasoning
    "CausalRelationType",
    "CausalQueryType",
    "CausalReasoningEngine",
    "CausalGraphBuilder",
    "CausalPatternExtractor",
    "CounterfactualEngine",
    "CausalExplanation",
    "CausalNode",
    "CausalEdge",
    "CausalPath",
    "CounterfactualScenario",
]
